/* Income Tax Rules, 1962 -- Rule citation registry for the TDS regime. Operationalises Chapter XVII-B
 * (form-and-manner of deduction certificates, quarterly statement schemas, time-bar for credit claim,
 * Form 12BB declaration shape, foreign-currency conversion, lower-deduction-cert procedure). */

import type { RuleCitation } from '../../types/citation.js';

export const itr = (ruleNumber: string, subRule?: string, note?: string): RuleCitation => ({
  kind: 'rule',
  ruleNumber,
  rules: 'IT_RULES_1962',
  ...(subRule !== undefined ? { subRule } : {}),
  ...(note !== undefined ? { note } : {}),
});

export const IT_RULES = {
  RULE_26: itr(
    '26',
    undefined,
    'Rate for foreign-currency conversion -- TDS computation in INR for non-resident payments',
  ),
  RULE_26B: itr(
    '26B',
    undefined,
    'Form 12BB -- employee declaration of investment proofs / HRA / housing-loan interest',
  ),
  RULE_30: itr(
    '30',
    undefined,
    'Time and manner of TDS payment -- 7th of next month (April-Feb), 30 April for March deductions',
  ),
  RULE_30_1A: itr(
    '30',
    '1A',
    'Mode of payment -- challan ITNS-281 (general) or challan-cum-statement (26QB / 26QC / 26QD / 26QE)',
  ),
  RULE_30_2: itr(
    '30',
    '2',
    'Specific timing exceptions -- 30 days for transactional 194-IA / 194-IB / 194M / 194S',
  ),
  RULE_31: itr(
    '31',
    undefined,
    'Form and manner of TDS certificates -- Form 16 (annual salary), 16A (quarterly non-salary), 16B / 16C / 16D / 16E (transactional), 27D (TCS)',
  ),
  RULE_31A: itr(
    '31A',
    undefined,
    'Quarterly statement of TDS -- 24Q / 26Q / 27Q. Due dates 31 July (Q1), 31 October (Q2), 31 January (Q3), 31 May (Q4 -- includes Annexure-II for salary)',
  ),
  RULE_31AA: itr(
    '31AA',
    undefined,
    'Quarterly statement of TCS -- 27EQ. Due dates 15 July / 15 October / 15 January / 15 May (tighter than TDS)',
  ),
  RULE_31AB: itr(
    '31AB',
    undefined,
    'Annual statement of TDS in Form 26AS -- generated by TRACES from quarterly returns',
  ),
  RULE_31ACB: itr('31ACB', undefined, 'Form 26B for refund of excess TDS by deductor'),
  RULE_37BA: itr(
    '37BA',
    undefined,
    'Credit for TDS in deductee ITR -- year-of-credit alignment with deductor filing',
  ),
  RULE_37BB: itr(
    '37BB',
    undefined,
    'Form 15CA / 15CB for non-resident remittances above prescribed thresholds',
  ),
  RULE_37BC: itr(
    '37BC',
    undefined,
    'Section 206AA bypass for non-residents -- alternative documentation (TIN / address / country / TRC) for interest / royalty / FTS / capital gains',
  ),
  RULE_26A: itr(
    '26A',
    undefined,
    'Form 12BA detail of perquisites and profits-in-lieu issued to the employee alongside Form 16',
  ),
  RULE_31A_4: itr(
    '31A',
    '4',
    '24Q Annexure-II per-employee Q4 salary disclosure (Section 17 perquisites + Section 10 exemptions + Section 16 deductions + Chapter VI-A + Section 89 relief)',
  ),
} as const;

export type ItRuleKey = keyof typeof IT_RULES;
